version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: codemirror
    versions:
    - 5.59.2
    - 5.59.3
    - 5.59.4
    - 5.60.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
